name: Infracost Scan

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  infracost-scan:
    runs-on: ubuntu-latest

    env:
      INFRACOST_CLI_AUTHENTICATION_TOKEN: ${{ secrets.INFRACOST_CLI_AUTHENTICATION_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3

      - name: Test Infracost authentication
        run: |
          infracost auth whoami
          infracost org current

      - name: Run Infracost Scan
        run: |
          infracost scan \
            --path ./aws/test/2_vpc_alb_ec2_lb
