name: Infracost Scan

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  infracost-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3

      - name: Configure Infracost
        run: |
          infracost configure set api_key ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost Scan
        run: |
          infracost scan \
            --path ./aws/test/2_vpc_alb_ec2_lb