name: Infracost

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  infracost:
    runs-on: ubuntu-latest
    env:
      INFRACOST_CLI_AUTHENTICATION_TOKEN: ${{ secrets.INFRACOST_CLI_AUTHENTICATION_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3

      - name: Run Infracost scan
        run: | 
          cd ./aws/test/2_vpc_alb_ec2_lb
          infracost scan \
            --path . \
            --json > infracost.json

      - name: Post comment to PR
        uses: infracost/actions/comment@v3
        with:
          path: ./aws/test/2_vpc_alb_ec2_lb/infracost.json
          behavior: update